server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  web:
    resources:
      add-mappings: false # 정적 리소스 매핑 비활성화
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**

        - id: order-service-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG # Netty 디버깅 활성화

management:
  endpoints:
    web:
      exposure:
        include: "*" # 모든 엔드포인트 노출