server:
  port: 8083

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3308/sparta
    username: root
    password: mysql3306
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: bzeXpcSoWC6x5gq5c2gk7DaifjAofTWMpwxUWQYqT5qaLHNHlZWWYyKTXUKqjVo8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true